#ifndef TMY_DEF_H
#define TMY_DEF_H

// All telemetry
enum tmy_index_e {
	// General Telemetry
	TMY_PARAM_ACCEPTED_PACKETS		= 0,
	TMY_PARAM_REJECTED_PACKETS		= 1,
	TMY_PARAM_LAST_OPCODE			= 2,
	TMY_PARAM_LAST_ERROR			= 3,

	TMY_PARAM_STATUS				= 4,

	// IMU

	// IMU (Raw)
	TMY_PARAM_IMU_RAW_ACCEL_X_B0, TMY_PARAM_IMU_RAW_ACCEL_X_B1, TMY_PARAM_IMU_RAW_ACCEL_X_B2, TMY_PARAM_IMU_RAW_ACCEL_X_B3,
	TMY_PARAM_IMU_RAW_ACCEL_Y_B0, TMY_PARAM_IMU_RAW_ACCEL_Y_B1, TMY_PARAM_IMU_RAW_ACCEL_Y_B2, TMY_PARAM_IMU_RAW_ACCEL_Y_B3,
	TMY_PARAM_IMU_RAW_ACCEL_Z_B0, TMY_PARAM_IMU_RAW_ACCEL_Z_B1, TMY_PARAM_IMU_RAW_ACCEL_Z_B2, TMY_PARAM_IMU_RAW_ACCEL_Z_B3,

	TMY_PARAM_IMU_RAW_GYRO_X_B0, TMY_PARAM_IMU_RAW_GYRO_X_B1, TMY_PARAM_IMU_RAW_GYRO_X_B2, TMY_PARAM_IMU_RAW_GYRO_X_B3,
	TMY_PARAM_IMU_RAW_GYRO_Y_B0, TMY_PARAM_IMU_RAW_GYRO_Y_B1, TMY_PARAM_IMU_RAW_GYRO_Y_B2, TMY_PARAM_IMU_RAW_GYRO_Y_B3,
	TMY_PARAM_IMU_RAW_GYRO_Z_B0, TMY_PARAM_IMU_RAW_GYRO_Z_B1, TMY_PARAM_IMU_RAW_GYRO_Z_B2, TMY_PARAM_IMU_RAW_GYRO_Z_B3,			

	TMY_PARAM_IMU_RAW_MAG_X_B0, TMY_PARAM_IMU_RAW_MAG_X_B1, TMY_PARAM_IMU_RAW_MAG_X_B2, TMY_PARAM_IMU_RAW_MAG_X_B3,
	TMY_PARAM_IMU_RAW_MAG_Y_B0, TMY_PARAM_IMU_RAW_MAG_Y_B1, TMY_PARAM_IMU_RAW_MAG_Y_B2, TMY_PARAM_IMU_RAW_MAG_Y_B3,
	TMY_PARAM_IMU_RAW_MAG_Z_B0, TMY_PARAM_IMU_RAW_MAG_Z_B1, TMY_PARAM_IMU_RAW_MAG_Z_B2, TMY_PARAM_IMU_RAW_MAG_Z_B3,

	TMY_PARAM_IMU_TEMP_B0, TMY_PARAM_IMU_TEMP_B1, TMY_PARAM_IMU_TEMP_B2, TMY_PARAM_IMU_TEMP_B3,

	// IMU (Est)
	TMY_PARAM_IMU_QUAT_X_B0, TMY_PARAM_IMU_QUAT_X_B1, TMY_PARAM_IMU_QUAT_X_B2, TMY_PARAM_IMU_QUAT_X_B3,
	TMY_PARAM_IMU_QUAT_Y_B0, TMY_PARAM_IMU_QUAT_Y_B1, TMY_PARAM_IMU_QUAT_Y_B2, TMY_PARAM_IMU_QUAT_Y_B3,
	TMY_PARAM_IMU_QUAT_Z_B0, TMY_PARAM_IMU_QUAT_Z_B1, TMY_PARAM_IMU_QUAT_Z_B2, TMY_PARAM_IMU_QUAT_Z_B3,
	TMY_PARAM_IMU_QUAT_W_B0, TMY_PARAM_IMU_QUAT_W_B1, TMY_PARAM_IMU_QUAT_W_B2, TMY_PARAM_IMU_QUAT_W_B3,

	// GPS

	TMY_PARAM_LAST
};

/* Status Interpretation */

#define STATUS_AHRS_FAIL			0x01
#define STATUS_GPS_FAIL				0x02

#endif
