#ifndef TMY_DEF_H
#define TMY_DEF_H

enum tmy_index_e {
	TMY_PARAM_ACCEPTED_PACKETS,
	TMY_PARAM_REJECTED_PACKETS,
	TMY_PARAM_LAST_OPCODE,
	TMY_PARAM_LAST_ERROR,

	TMY_PARAM_LAST
};

#endif
